#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

AWS_PROFILE_NAME="${AWS_PROFILE:-news-monitor-dev}"
AWS_REGION_NAME="eu-central-1"
AWS_ACCOUNT_ID="385740679214"
DB_HOST_NAME="chat-rag-postgres.cfqss0oiuimn.eu-central-1.rds.amazonaws.com"
EXECUTION_POLICY_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:policy/chat-rag-ecs-read-openai-secret"
GITHUB_ROLE_NAME="chat-rag-github-actions"
TEMP_FILES=()

cleanup_temp_files() {
  local path
  for path in "${TEMP_FILES[@]}"; do
    [[ -n "$path" && -f "$path" ]] && rm -f -- "$path"
  done
}
trap cleanup_temp_files EXIT

make_temp_file() {
  WIZARD_TEMP_FILE=$(mktemp)
  chmod 600 "$WIZARD_TEMP_FILE"
  TEMP_FILES+=("$WIZARD_TEMP_FILE")
}

urlencode() {
  DB_PASSWORD_FOR_ENCODING="$1" node -e 'process.stdout.write(encodeURIComponent(process.env.DB_PASSWORD_FOR_ENCODING))'
}

upsert_secret() {
  local name="$1" value="$2" secret_file
  make_temp_file
  secret_file="$WIZARD_TEMP_FILE"
  printf '%s' "$value" > "$secret_file"

  if aws secretsmanager describe-secret \
      --profile "$AWS_PROFILE_NAME" \
      --region "$AWS_REGION_NAME" \
      --secret-id "$name" >/dev/null 2>&1; then
    aws secretsmanager put-secret-value \
      --profile "$AWS_PROFILE_NAME" \
      --region "$AWS_REGION_NAME" \
      --secret-id "$name" \
      --secret-string "file://${secret_file}" >/dev/null
    printf '  %s✓ updated%s %s\n' "$GREEN" "$RESET" "$name"
  else
    aws secretsmanager create-secret \
      --profile "$AWS_PROFILE_NAME" \
      --region "$AWS_REGION_NAME" \
      --name "$name" \
      --secret-string "file://${secret_file}" >/dev/null
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$name"
  fi
}

banner "Chat RAG · PostgreSQL AWS prerequisites"

stage "AWS account preflight"
say "This wizard changes only two DB secrets and two existing IAM policies."
say "Profile: $AWS_PROFILE_NAME · Region: $AWS_REGION_NAME · Expected account: $AWS_ACCOUNT_ID"
step "If this profile is not authenticated, stop and run: aws sso login --profile $AWS_PROFILE_NAME"
ACTUAL_ACCOUNT_ID=$(aws sts get-caller-identity \
  --profile "$AWS_PROFILE_NAME" \
  --query Account \
  --output text)
if [[ "$ACTUAL_ACCOUNT_ID" != "$AWS_ACCOUNT_ID" ]]; then
  warn "Authenticated account is $ACTUAL_ACCOUNT_ID, expected $AWS_ACCOUNT_ID."
  exit 1
fi
printf '  %s✓ correct AWS account%s\n' "$GREEN" "$RESET"
pause "Continue to database secrets?"

stage "Secrets Manager: application and migration URLs"
say "Enter the exact passwords already assigned to the PostgreSQL roles."
warn "If you literally used MIGRATE_PASSWORD or APP_PASSWORD, stop and rotate those role passwords first."
ask_secret APP_DB_PASSWORD "Password for chat_rag_app:"
ask_secret MIGRATE_DB_PASSWORD "Password for chat_rag_migrate:"
if [[ -z "$APP_DB_PASSWORD" || -z "$MIGRATE_DB_PASSWORD" ]]; then
  warn "Both passwords are required. Nothing was changed."
  exit 1
fi
APP_DATABASE_URL="postgresql://chat_rag_app:$(urlencode "$APP_DB_PASSWORD")@${DB_HOST_NAME}:5432/postgres"
MIGRATE_DATABASE_URL="postgresql://chat_rag_migrate:$(urlencode "$MIGRATE_DB_PASSWORD")@${DB_HOST_NAME}:5432/postgres"
unset APP_DB_PASSWORD MIGRATE_DB_PASSWORD
say "The secret values will be full connection URLs. TLS verification is enforced by the application, not URL flags."
say "No value is written to the repo, .env, GitHub, or terminal output."
if ! confirm "Create or update chat-rag/db/app and chat-rag/db/migrate?"; then
  warn "Secrets were not changed."
  exit 1
fi
upsert_secret "chat-rag/db/app" "$APP_DATABASE_URL"
upsert_secret "chat-rag/db/migrate" "$MIGRATE_DATABASE_URL"
unset APP_DATABASE_URL MIGRATE_DATABASE_URL
pause "Secrets are ready. Continue to the ECS execution role policy?"

stage "IAM: ECS execution role can inject DB secrets"
say "This replaces the current managed-policy document with least-privilege access to OpenAI, app DB, and migration DB secrets."
say "The obsolete admin secret chat-rag/db/postgres is deliberately removed from this execution role."
make_temp_file
EXECUTION_POLICY_FILE="$WIZARD_TEMP_FILE"
cat > "$EXECUTION_POLICY_FILE" <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ReadChatRagRuntimeSecrets",
      "Effect": "Allow",
      "Action": "secretsmanager:GetSecretValue",
      "Resource": [
        "arn:aws:secretsmanager:eu-central-1:385740679214:secret:chat-rag/openai-*",
        "arn:aws:secretsmanager:eu-central-1:385740679214:secret:chat-rag/db/app-*",
        "arn:aws:secretsmanager:eu-central-1:385740679214:secret:chat-rag/db/migrate-*"
      ]
    }
  ]
}
JSON
if ! confirm "Create and activate a new version of $EXECUTION_POLICY_ARN?"; then
  warn "Execution role policy was not changed."
  exit 1
fi
aws iam create-policy-version \
  --profile "$AWS_PROFILE_NAME" \
  --policy-arn "$EXECUTION_POLICY_ARN" \
  --policy-document "file://${EXECUTION_POLICY_FILE}" \
  --set-as-default >/dev/null
printf '  %s✓ ECS execution role policy updated%s\n' "$GREEN" "$RESET"
pause "Continue to the GitHub Actions deployment policy?"

stage "IAM: GitHub Actions can run and inspect migration tasks"
say "This preserves the existing API deployment permissions and adds only RunTask/DescribeTasks for migrations."
make_temp_file
GITHUB_POLICY_FILE="$WIZARD_TEMP_FILE"
cat > "$GITHUB_POLICY_FILE" <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "RegisterApiTaskDefinition",
      "Effect": "Allow",
      "Action": [
        "ecs:RegisterTaskDefinition"
      ],
      "Resource": "*"
    },
    {
      "Sid": "DeployApiService",
      "Effect": "Allow",
      "Action": [
        "ecs:UpdateService",
        "ecs:DescribeServices"
      ],
      "Resource": "arn:aws:ecs:eu-central-1:385740679214:service/chat-rag-cluster/chat-rag-api-service"
    },
    {
      "Sid": "RunApiMigrationTask",
      "Effect": "Allow",
      "Action": "ecs:RunTask",
      "Resource": "arn:aws:ecs:eu-central-1:385740679214:task-definition/chat-rag-api-migration:*",
      "Condition": {
        "ArnEquals": {
          "ecs:cluster": "arn:aws:ecs:eu-central-1:385740679214:cluster/chat-rag-cluster"
        }
      }
    },
    {
      "Sid": "InspectApiMigrationTask",
      "Effect": "Allow",
      "Action": "ecs:DescribeTasks",
      "Resource": "*"
    },
    {
      "Sid": "PassApiTaskRoles",
      "Effect": "Allow",
      "Action": "iam:PassRole",
      "Resource": [
        "arn:aws:iam::385740679214:role/chat-rag-ecs-task-execution",
        "arn:aws:iam::385740679214:role/chat-rag-ecs-task"
      ],
      "Condition": {
        "StringEquals": {
          "iam:PassedToService": "ecs-tasks.amazonaws.com"
        }
      }
    }
  ]
}
JSON
if ! confirm "Update inline policy chat-rag-ecs-deploy on $GITHUB_ROLE_NAME?"; then
  warn "GitHub Actions role policy was not changed."
  exit 1
fi
aws iam put-role-policy \
  --profile "$AWS_PROFILE_NAME" \
  --role-name "$GITHUB_ROLE_NAME" \
  --policy-name "chat-rag-ecs-deploy" \
  --policy-document "file://${GITHUB_POLICY_FILE}"
printf '  %s✓ GitHub Actions deployment policy updated%s\n' "$GREEN" "$RESET"
pause "Continue to the final read-only verification?"

stage "Verify prerequisites"
for secret_name in chat-rag/db/app chat-rag/db/migrate; do
  aws secretsmanager describe-secret \
    --profile "$AWS_PROFILE_NAME" \
    --region "$AWS_REGION_NAME" \
    --secret-id "$secret_name" \
    --query '{Name:Name,ARN:ARN}' \
    --output json
done
aws ecs describe-services \
  --profile "$AWS_PROFILE_NAME" \
  --region "$AWS_REGION_NAME" \
  --cluster chat-rag-cluster \
  --services chat-rag-api-service \
  --query 'services[0].networkConfiguration.awsvpcConfiguration' \
  --output json
say "Expected network: private subnets, sg-0789d406370b17d9f, assignPublicIp DISABLED."
say "No GitHub secret or variable is required; GitHub continues to authenticate through OIDC."
say "Do not run a migration manually yet. The feature branch will add the image command, Task Definition, and blocking workflow step."
pause "AWS prerequisites are complete."

finish
